Git lecture03
nekoppy/RaiseTech pull request #2
Opened 2024-01-17 02:24 UTC by nekoppy

お世話になっております。
第3回課題になります。
確認をお願い致します。

2024-01-17 04:18 UTC, MasatoshiMizumoto requested changes
コメント入れました！ご対応お願いします！！

2024-01-17 04:18 UTC, MasatoshiMizumoto commented on git-lecture03.md
> +<img width="1299" alt="スクリーンショット 2024-01-10 15 50 31" src="https://github.com/nekoppy/RaiseTech/assets/53550588/ec217dc9-a2c5-434c-b755-a9aa460cf161">
この画像の書き方だと例えばGitHubを利用廃止して別のGitサービスに引っ越したとき消えてしまうのでNGとさせてください！
画像もバージョン管理して内部リンクとして対応ください！

2024-01-17 06:19 UTC, nekoppy commented on git-lecture03.md
> +<img width="1299" alt="スクリーンショット 2024-01-10 15 50 31" src="https://github.com/nekoppy/RaiseTech/assets/53550588/ec217dc9-a2c5-434c-b755-a9aa460cf161">
修正してみました。
確認をお願いいたします。

2024-01-17 06:28 UTC, MasatoshiMizumoto requested changes
コメントいれましたのでご対応お願いします！！

2024-01-17 06:28 UTC, MasatoshiMizumoto commented on git-lecture03.md
> +  ＝＞sudo service mysqld stopで停止し、sudo service mysqld startで起動OK。
引き続きアクセス可能か確認してほしい、という意図なので、コマンドを書いてもらうのも良いのですが必要な情報が不足していますね！

2024-01-18 12:07 UTC, nekoppy commented on git-lecture03.md
> +  ＝＞sudo service mysqld stopで停止し、sudo service mysqld startで起動OK。
画像入れて、修正してみました。
確認をよろしくお願いします。

2024-01-18 13:03 UTC, MasatoshiMizumoto approved these changes
LGTM!

2024-01-18 13:11 UTC, merged